# Site Settings
timezone: Asia/Ho_Chi_Minh
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor", "README", "README.md", "LICENSE"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap, jekyll-admin]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin
highlighter: rouge
markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3
sass:
  style: compressed

# Site Data
url: 'https://tuannm.com' # the base hostname & protocol for your site, e.g. http://example.com
#baseurl: '/' # the subpath of your site when run on GitHub
baseurl: '' # the subpath of your site when run to local

# Seo Data
title: Tuan.N.M
description: "Web Designer & Developer from Hanoi, Vietnam"
keywords: 'tuannm,front-end,developer,blog,designer'
type: Person
image: /assets/images/tuannm.png
author:
  name: Tuan
  full_name: Tuan Nguyen Manh
  job_title: Front-end Developer & Designer
  location: Hanoi, Vietnam
  email: tuannm.cntt93@gmail.com
  social_links:
    - name: github
      url: https://github.com/tuannm93
    - name: linkedin
      url: https://www.linkedin.com/in/tuannm93
#    - name: facebook
#      url: https://www.facebook.com/tuannm93
#    - name: instagram
#      url: https://www.instagram.com/tuannm93
#    - name: stackoverflow
#      url: https://stackoverflow.com/users/4454936/nguyen-manh-tuan
#    - name: twitter
#      url: https://twitter.com/tuannm993
#    - name: vk
#      url: https://vk.com/tuannm93

home:
  section0: # something
  section1: <h1>Tuan.N.M</h1>
  section2: <h2>I am a web developer focusing on front-end development. Always hungry to keep learning.</h2> #<h2>Web Designer & Developer from Hanoi, Vietnam</h2>

google_tag_manager: GTM-KBJFJRZ

paths:
  home: /
  blog: https://blog.tuannm.com
